version: 2.1

executors:
  ruby-main:
    docker:
      - image: cimg/ruby:3.2.2
    working_directory: ~/app

jobs:
  test:
    executor: ruby-main
    parallelism: 2
    steps:
      - checkout
      - run: bundle install
      - run:
          command: |
            bundle exec rspec \
              --format RspecJunitFormatter \
              --out test-results/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: rspec-results

workflows:
  test:
    jobs:
      - test
